version: '3.5'
services:
  db-checker:
    build: .
    ports:
      - "8000:8000"
  db-master:
    image: mysql:latest
    container_name: "db-master"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=root
    networks:
      - devops_network
  db-slave:
    image: mysql:latest
    container_name: "db-slave"
    depends_on:
      - db-master
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=root
    networks:
      - devops_network
networks:
  devops_network:
    external: false